/***************************************************************************************
 * LtGAudioLinks.h
 *
 * Copyright (c) 2010 Lightning Gaming, Inc.
 * All Rights Reserved.
 *
 * Permission to use, copy, modify, and distribute this software 
 * is hereby NOT granted. Please refer to the file "copyright.html"
 * for further important copyright and licensing information.
 *
 * IMPORTANT: This file is auto generated by BuildAudioLinks.pl
 *            Any manual changes will likely be overwritten.
 ***************************************************************************************/
#pragma once

const char* const szSOUNDBANKS[] = 
{
    "basegame",
    NULL
};
const char *const szWAVEDEPENDENCIES[1][2] =
{
    { "basegame", NULL,  },
};
