#ifndef __XACT_PROJECT_HARVESTBOOM__
#define __XACT_PROJECT_HARVESTBOOM__

typedef enum
{
    XACT_VARIABLE_NUMCUEINSTANCES = 0,
    XACT_VARIABLE_ATTACKTIME = 1,
    XACT_VARIABLE_RELEASETIME = 2,
    XACT_VARIABLE_ORIENTATIONANGLE = 3,
    XACT_VARIABLE_DOPPLERPITCHSCALAR = 4,
    XACT_VARIABLE_SPEEDOFSOUND = 5,
    XACT_VARIABLE_DISTANCE = 6,
} XACT_VARIABLE;

#define XACT_VARIABLE_COUNT 7

typedef enum
{
    XACT_WAVEBANK_BASEGAME_ROOSTER_CROWING = 0,
    XACT_WAVEBANK_BASEGAME_FARM_NIGHT_16BIT = 1,
    XACT_WAVEBANK_BASEGAME_FARM_DAYTIME_16BIT = 2,
} XACT_WAVEBANK_BASEGAME;

#define XACT_WAVEBANK_BASEGAME_ENTRY_COUNT 3

typedef enum
{
    XACT_CUE_BASEGAME_ROOSTER_CROWING = 0,
    XACT_CUE_BASEGAME_FARM_DAYTIME_16BIT = 1,
    XACT_CUE_BASEGAME_FARM_NIGHT_16BIT = 2,
} XACT_CUE_BASEGAME;

#define XACT_CUE_BASEGAME_ENTRY_COUNT 3

#endif // __XACT_PROJECT_HARVESTBOOM__
